### ISSUE TITLE
Create a CLI Tool for ModelGenerator

### ISSUE THREAD

**Issue by Davilink** [anthonyreilly/NetCoreForce#18]
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

**Comment by anthonyreilly** [comment]
ModelGenerator has been repackaged as a .NET CLI tool, v3 beta is available
dotnet tool install --global NetCoreForce.ModelGenerator --version 3.0.0-Beta
