### ISSUE TITLE
ForceClient.TestConnection() not implemented

### ISSUE THREAD

**Issue by charliefoxtwo** [anthonyreilly/NetCoreForce#6]
Today we found out the hard way that the `TestConnection()` method is not yet implemented. Are there any plans to either implement this, document that the method is not implemented, or potentially add an `ObsoleteAttribute` to warn developers not to use this method? We had it alongside a null-coalescing operator, so we didn't notice until the one time our `ForceClient` object wasn't actually null.

ForceClient.cs lines 69-72:
```
public bool TestConnection()
{
    throw new NotImplementedException();
}
```

**Comment by anthonyreilly** [comment]
Sorry about that, I'll get that implemented and published in the next couple days.

**Comment by charliefoxtwo** [comment]
This is excellent, thank you!
